### ISSUE TITLE
Can't use shex in a browser

### ISSUE THREAD

**Issue by matthieu-fesselier** [shexSpec/shex.js#39]
I can't use `shex.js` in a browser. When I import it with jspm:
```html
<script type="module" src="https://dev.jspm.io/shex"></script>
```
I get this error:
```
N3.dew.js:17 Uncaught ReferenceError: require is not defined
    at dew (N3.dew.js:17)
    at ShExUtil.dew.js:15
    at dew (ShExUtil.dew.js:1993)
    at ShExJison.dew.js:3052
    at dew (ShExJison.dew.js:4123)
    at ShExParser.dew.js:16
    at dew (ShExParser.dew.js:81)
    at dew (shex.dew.js:17)
    at shex:2
```
Is there another way of doing this?

**Comment by ericprud** [comment]
apologies for the delay.
Because of some frustrating (capricious?) differences between node and browser environments, the traditional way of embedding node libraries in a browser is to [webpack](https://www.npmjs.com/package/webpack) or [browserify](https://www.npmjs.com/package/browserify) them. The `package.json` in whatever branch you are should have a script for at least one of those.

**Comment by sylvainlb** [comment]
Actually we develop our applications in a ES6 module way and nowadays it works quite well. It's a shame we can't use shex.js in a modern ES6 context.

**Comment by ericprud** [comment]
I'm happy to try a PR out on the [supported node versions](https://github.com/shexSpec/shex.js/blob/ASasShExJ/.travis.yml#L6-L8) and a couple browsers. I guess we'd have to write off IE.

**Comment by sylvainlb** [comment]
Ok, thanks, we'll have a look!

**Comment by matthieu-fesselier** [comment]
Finally managed to make it work with v0.9.2, thanks!

**Comment by ericprud** [comment]
I've been experimenting with ES6 modules. My concern is that while I can use AMDs with ES6 modules, I don't have a good feel for what I write off if I switch entirely to modules, i.e. what browsers don't support them yet. Have you done that research?

**Comment by sylvainlb** [comment]
They're fairly well supported, except by IE11: https://caniuse.com/#feat=es6-module

We decided we would not support IE11, although a transpiling fallback is possible.

**Comment by Yucukof** [comment]
Hello gentlemen,

Unearthing this old closed issue, because I'm finding myself in a similar situation.

I'm using [Shex-methods](https://github.com/ludwigschubi/shex-methods) which is using Shex.js internally.  
It all goes well server-side, but when I'm trying to bring this into my webapp, it simply breaks.
I have tried and added all polyfills that I could think of, to no avail.

In one of the above reply, I see you mention `browserify`.

> Because of some frustrating (capricious?) differences between node and browser environments, the traditional way of embedding node libraries in a browser is to [webpack](https://www.npmjs.com/package/webpack) or [browserify](https://www.npmjs.com/package/browserify) them. The `package.json` in whatever branch you are should have a script for at least one of those.

I happen to have found the script,
```
"browserify node_modules/shex/shex.js -s ShEx -o node_modules/shex/browser/shex-browserify.js && uglifyjs node_modules/shex/browser/shex-browserify.js --comments -mco browser/shex-browserify.min.js
```
though I'm not very sure how to embed this afterwards.

Would you perhaps have some guidance to share with me on this?
Maybe am I missing one of the resolve.fallback or something?

If of any use, the source code is hosted on [this repo](https://github.com/Yucukof/edu-solid-authorization/tree/HBA/RDF/src)

Thank you for your insight.
