### ISSUE TITLE
Comments not parsing right for external references

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex.js#4]
```turtle
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX fhirvs: <http://hl7.org/fhir/ValueSet/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
BASE <http://hl7.org/fhir/shape/>

fhirvs:event-timing EXTERNAL

# Codes identifying the types of relationships between two plans.
``` 

Fails with error:

```
(6): Parse error on line 6:
...fhirvs:event-timing EXTERNAL# Codes id
```

**Comment by ericprud** [comment]
This is fixed in TEisSE and accessors.

ShExJison in master creates a
  {type:"Schea", valueExprDefns[<shapeName]: null}
but the validator would fail on references to <shapeName>.
The TEisSE and accessors story is better. There are tests to round-trip ShExC-ShExJ and validation tests of external shapes. This required a convention for a [.shexternal file](/../../../shexTest/blob/TEisSE/schemas/shapeExtern.shextern) which is just a regular ShExC file to provide a testable EXTERN shape. This was done to minimize the testing machinery but in actual deployments, EXTERNs would have some user-defined functions to validate the supplied node/shape pairs.
