### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by ross-spencer** [shexSpec/shex.js#78]
I'm sorry I don't know how to interpret these further, but downloading the library today and running the commands as described: `cd node_modules/shex && npm install && npm test ` I'm seeing the tests fail locally. I've attached the results. Any other help here appreciated. 

[2020-08-15-test_results.txt](https://github.com/shexSpec/shex.js/files/5079356/2020-08-15-test_results.txt)

**Comment by ross-spencer** [comment]
Thanks Eric. I appreciate it.

**Comment by ericprud** [comment]
hi @ross-spencer, i've updated the tests to use cloned git repos instead of the published NPM version. I've also updated the NPM version but, since different branches of `shex.js` are tested by corresponding branches of `shexTest`, it made more sense to just use the repo branches. Hopefull the [README section](..#test) is relatively clear about that. Feel free to close this issue if that does the job (or issue PRs to improve it).

**Comment by ross-spencer** [comment]
I've been having a look at this today, the docs look great and the behavior has definitely changed. I haven't got tests working yet, but I suspect this is more to do with my abilities node. I'll keep playing, and intend to use the library more, but I'll close this now and try and drop some notes back if I find the resolution locally.

**Comment by ericprud** [comment]
you might need to wipe out your modules and reinstall
https://github.com/shexSpec/shex.js/blob/master/bin/reinstallDeps.sh
